enable: true

endpoints:
  "/path1":
    strategy: round-robin # random, weighted, round-robin
    urls:
      - url: "https://example.com/api1"
        # Optional: socks5, username, password
        socks5: "127.0.0.1:1080"
        username: "user1"
        password: "pass1"
      - url: "https://example.com/api2"
      - url: "https://example.com/api3"
    ban:
      - match : ["too many requests"]
        duration: 60
      - match : ["exceeded monthly allowance"]
        duration: 3600

  "/path2":
    strategy: weighted
    urls:
      - url: "https://example.com/api1"
        weight: 50 # Required for weighted strategy
      - url: "https://example.com/api2"
        weight: 30
      - url: "https://example.com/api3"
        weight: 20

# Applies to all endpoints and is overridden locally
global_ban:
  - match: ["too many requests"]
    duration: 60 # in seconds
  - match: ["exceeded monthly allowance"]
    duration: 3600
